"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./midi2dmx.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
           'packages': [ 'simplecoremidi', 'ola', 'objc', 'rumps'],
           'plist' : {
               'LSUIElement': True,

           }}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=[ 'py2app', 'simplecoremidi', 'rumps'],
)
